DO $$
DECLARE
    table_name TEXT;
BEGIN
    FOREACH table_name IN ARRAY ARRAY[
        'navigation_items',
        'customer_profile_snapshots',
        'notification_messages',
        'search_suggestions',
        'search_documents',
        'notice_posts',
        'wallet_balance_snapshots',
        'benefit_programs',
        'benefit_claim_requests',
        'home_shortcuts',
        'promotion_campaigns',
        'ledger_transaction_snapshots',
        'user_ranking_snapshots',
        'booth_ranking_snapshots',
        'festival_banner_assets',
        'pay_barcode_tokens',
        'booth_category_settings',
        'booth_banner_assets',
        'booth_profiles',
        'product_catalog_items',
        'product_view_events',
        'booth_checkin_events',
        'cart_items',
        'customer_order_snapshots',
        'favorite_targets',
        'customer_inquiries',
        'share_events',
        'worldcup_prediction_entries',
        'worldcup_prediction_settlement_runs',
        'feature_flags',
        'booth_staff_profiles',
        'inventory_adjustment_requests',
        'product_purchase_limits',
        'pickup_vouchers',
        'payment_intent_snapshots',
        'payment_snapshots',
        'booth_visit_events',
        'booth_settlement_runs',
        'export_jobs',
        'festival_profiles',
        'venue_maps',
        'user_directory_entries',
        'user_import_jobs',
        'role_definitions',
        'role_assignment_entries',
        'wallet_adjustment_requests',
        'ledger_export_jobs',
        'reward_rule_definitions',
        'file_upload_requests',
        'worldcup_team_profiles',
        'worldcup_match_schedules',
        'worldcup_match_lineups',
        'worldcup_match_stats',
        'audit_log_entries',
        'system_job_states',
        'incident_reports',
        'ranking_rule_definitions',
        'github_commit_events',
        'github_app_installation_events',
        'internal_account_snapshots',
        'analytics_impression_events',
        'inquiry_reply_messages'
    ]
    LOOP
        EXECUTE format(
            'CREATE INDEX IF NOT EXISTS %I ON %I USING GIN (payload jsonb_path_ops)',
            'idx_' || table_name || '_payload_gin',
            table_name
        );
    END LOOP;
END $$;
